version: '2.23'

services:
  server: 
    build: .
    volumes:
      - ~/digitalchemistry/image-data:/usr/dist/client/images
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition:
          service_healthy      
    environment:
      - PUBLIC_FILE_PATH=${PUBLIC_FILE_PATH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - JWT_SECRET=${JWT_SECRET}

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/digitalchemistry/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 5
